name: easy_json_dart
description: A starting point for Dart libraries or applications.
version: 1.0.1
homepage: https://github.com/373518155/EasyJSONDart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  sprintf: "^4.0.0"
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
